twig:
    default_path: '%kernel.project_dir%/templates'
    # les fichiers de themes de formulaire se trouvent dans :  /app/vendor/symfony/twig-bridge/Resources/views/Form/bootstrap_5_layout.html.twig
    form_themes: ['bootstrap_5_layout.html.twig']
when@test:
    twig:
        strict_variables: true
